Реализация алгоритма с официантом
mglukhikh/kilosophers pull request #1
Opened 2018-05-17 21:57 UTC by SerVB

Простое решение проблемы с помощью официанта.

2018-05-17 22:03 UTC, SerVB commented
Запуск: `com.github.servb.kotlin.kilosophers.RunnerKt.main`. Исполнение бесконечное, поэтому выход с помощью `⛔` (принудительное завершение процесса).
Результат: строки вида `номер_тика: номер_философа` на тех тиках, когда какой-либо философ ест.

Пример:
![image](https://user-images.githubusercontent.com/20105593/40205911-9a5c0c6e-5a36-11e8-860b-1c3db8fea596.png)

2018-05-17 22:29 UTC, SerVB commented
Добавил распознавание ситуации лока, потому что не при каждом запуске программа что-то выводила. Не понимаю: либо на первом же тике происходит лок, либо работает долго и не блокируется, т.е. кажется, что локов больше и не будет.

2018-05-17 22:48 UTC, SerVB commented
Добавил костыль: если лок случается на первом тике, происходит переигровка, пока лок не будет устранен. Вроде бы, сейчас работает при любом запуске.

![image](https://user-images.githubusercontent.com/20105593/40207481-60f378ac-5a3d-11e8-94a8-acb4ddc6cd29.png)

Что-то мне подсказывает, что я не до конца понял эту тему... В любом случае, спасибо за увлекательную задачу!

2018-05-20 14:15 UTC, mglukhikh requested changes
Написал немножко замечаний по тексту PR. Основные вещи мы с вами обсуждали

2018-05-20 14:15 UTC, mglukhikh commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Table.kt
> +    val freeForks get() = forks.filter { it.isFree() }.size
Здесь лучше просто `forks.count { it.isFree() }`

2018-05-20 14:15 UTC, mglukhikh commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Table.kt
> +    val forks = Array(n, { AtomicFork() })
Лучше выносить лямбды за круглые скобки

2018-05-20 14:15 UTC, mglukhikh commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +            if (tick == 1) {  // TODO: Fix this workaround
Этот момент подробно обсуждали лично, конечно, нужно править

2018-05-20 14:15 UTC, mglukhikh commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +    val eatStat = IntArray(n, { 0 })
И здесь лямбду лучше вынести за скобки

2018-05-20 14:15 UTC, mglukhikh commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +        for (i in table.kilosophers.indices) {
Есть возможность в одном цикле перебрать и индексы и философов

```
for ((i, nowKilosopher) in table.kilosophers.withIndex()) { ... }
```
```

2018-05-20 14:15 UTC, mglukhikh commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +        Thread.sleep(500)
Учитывая, что это задание по корутинам, лучше бы обойтись без операций с потоками

2018-05-22 12:05 UTC, SerVB commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +        Thread.sleep(500)
Вы имеете в виду, что надо просто убрать эту строку?

2018-05-22 12:07 UTC, SerVB commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +            if (tick == 1) {  // TODO: Fix this workaround
Пока исправить не удается. См. 8b35317. Если дедлайн до завтра, то боюсь, что не успею.

2018-05-22 12:35 UTC, mglukhikh commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +        Thread.sleep(500)
Нет. Мы же обсуждали, что можно вполне корректно дождаться завершения работы философов без этого sleep-а.

2018-05-22 17:47 UTC, SerVB commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +        Thread.sleep(500)
Прошу прощения, но я не помню конкретики по этому моменту... Пожалуйста, скажите, что здесь лучше сделать?

2018-05-23 09:23 UTC, mglukhikh commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +        Thread.sleep(500)
Учитывая, что `act` возвращает `Job`, его можно просто запомнить и в этом месте всем `Job` сделать `join`.

2018-05-25 12:28 UTC, SerVB commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +        Thread.sleep(500)
Спасибо! Кажется, удалось реализовать все запрошенные изменения. Пожалуйста, посмотрите!

2018-05-25 12:56 UTC, SerVB commented on src/main/kotlin/com/github/servb/kotlin/kilosophers/Runner.kt
> +            if (tick == 1) {  // TODO: Fix this workaround
Дедлайн вообще до понедельника был... Ну, в 3a59e41 удалось сделать вроде бы нормальную реализацию.

2019-04-25 09:51 UTC, closed without merging